### ISSUE TITLE
ensure correct GDTF parsing

### ISSUE THREAD

**Issue by vanous** [MomentFactory/Omniverse-MVR-GDTF-converter#1]
Hi all,

i just discovered your repo, super cool!

Small note: when parsing GDTFs, make sure to start from DMX Modes,  choose a DMX mode and from this selected mode get the linked geometry, then follow the geometry tree, make sure to multiple geometry references, then only assign channels from the DMX mode :) . Do not repeat the mistake we did in [BlenderDMX](https://github.com/open-stage/blender-dmx) at first - looking for geometries by their names and so on... as that is not how it works. You can see for example [here](https://github.com/open-stage/python-gdtf/blob/master/pygdtf/utils/__init__.py#L153) how to get channels and so on. That implementation also correctly uses DMX Breaks and Break Overwrites. Our current design is correctly processing GDTF but we still need to rework geometry placements in Blender as we need better parent-child structure and the initial implementation in Blender was also not good (unrelated to GDTF). This has already been happening in BlenderDMX development branch.

If you plan to stick to python for GDTF parsing, you can use our [pygdtf](https://github.com/open-stage/python-gdtf) library, it is work in progress but already does quite a few things correctly.

Good luck with your project!

**Comment by agrosjea** [comment]
Hello Vanous. 
You certainly just discovered it because we opened it yesterday ! 
Happy you found us so fast, because the information you provide is very valuable. And It's actually great to hear that other people in the open source community are interested in GDTF/MVR.
FYI Repo is still in construction and we are currently working on our first public release we have a couple of bugs we like to fixe before it is usable with Omniverse.
Best regards.
